/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import Clases.Comprobacion;

import Repository.impl.ApiRestRepository;



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 * Interfaz principal de la aplicación.
 * @author israelmedrano
 */
public class Reservas extends javax.swing.JFrame {
int idActividad;
Object idCliente;
    /**
     * Creates new form Principal. Obtengo el objeto enviado desde la otra clase y vinculo las dos tablas que aparecerán en el JFrame, cargo las reservas ya existentes
     */
    public Reservas(java.awt.Frame parent, boolean modal, int idActividad) {
        this.idActividad = idActividad;
        
        initComponents();
        
        modelo = (DefaultTableModel) busquedaClientes.getModel();
        modelo2 = (DefaultTableModel) reservasClientes.getModel();
        
        
        //conexion.cargarReservas(modelo2, idActividad);
        ApiRestRepository apiRepository = new ApiRestRepository();
        apiRepository.cargarReservas(modelo2, idActividad);
        
        
  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        foto2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservasClientes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        busquedaClientes = new javax.swing.JTable();
        btnAnadir = new javax.swing.JButton();
        cbxBotella = new javax.swing.JComboBox<>();
        cbxConexion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Amatic SC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SubApp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(291, 291, 291)
                .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 983, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        reservasClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Botella", "Conexión"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reservasClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reservasClientes);

        jLabel2.setText("Nombre:");

        jLabel3.setText("Capacidad de la botella:");

        jLabel4.setText("Conexión de la botella:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        busquedaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Nª buceos", "Certificación"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        busquedaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busquedaClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(busquedaClientes);

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        cbxBotella.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione botella", "10L", "12L", "15L" }));

        cbxConexion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione conexión", "DIN", "INT" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(btnAnadir))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxBotella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxBotella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxConexion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnAnadir)
                                .addGap(33, 33, 33)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservasClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasClientesMouseClicked

      

        // TODO add your handling code here:
    }//GEN-LAST:event_reservasClientesMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed




        modelo.setRowCount(0);
        
        if(Comprobacion.vacio(txtNombre)){
            
         
            
            apirestrepository.cargarClientes(modelo);
            
        }
        //else conexion.busquedaClientes(modelo, txtNombre.getText());
        else apirestrepository.busquedaClientes(modelo, txtNombre.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed

  /**
 * Selecciona la botella adecuada basada en las selecciones realizadas en los JComboBox {@code cbxBotella} y {@code cbxConexion}.
 * 
 * Este segmento de código determina qué botella se debe utilizar para la actividad de buceo,
 * dependiendo de las opciones seleccionadas por el usuario. A continuación, valida que ambas selecciones
 * sean válidas antes de registrar la reserva en el repositorio.
 * 
 * Si alguna selección es inválida, se muestra una alerta correspondiente. En caso contrario, se
 * intenta registrar la reserva utilizando el método {@link ApiRestRepository#registraReserva(int, int, int)},
 * pasando el ID de la actividad, el ID del cliente y el ID de la botella seleccionada.
 * 
 * Se muestran mensajes al usuario dependiendo del resultado de la operación de registro:
 * - Un error en la inscripción.
 * - Un registro exitoso.
 * - Un mensaje indicando que el cliente ya está registrado en la actividad.
 * 
 * @throws IllegalArgumentException si las selecciones de botella o conexión son inválidas.
 *                                   (Nota: Ajustar según el manejo de errores necesario).
 *
 * @see ApiRestRepository
 */

    // Selecciono la botella adecuada
    int botella = -1;
    if (cbxBotella.getSelectedIndex() == 1 && cbxConexion.getSelectedIndex() == 1) botella = 1;
    else if (cbxBotella.getSelectedIndex() == 1 && cbxConexion.getSelectedIndex() == 2) botella = 2;
    else if (cbxBotella.getSelectedIndex() == 2 && cbxConexion.getSelectedIndex() == 1) botella = 3;
    else if (cbxBotella.getSelectedIndex() == 2 && cbxConexion.getSelectedIndex() == 2) botella = 4;
    else if (cbxBotella.getSelectedIndex() == 3 && cbxConexion.getSelectedIndex() == 1) botella = 5;
    else if (cbxBotella.getSelectedIndex() == 3 && cbxConexion.getSelectedIndex() == 2) botella = 6;

    // Validaciones de selección
    if (Comprobacion.select(cbxBotella)) {
        Comprobacion.alertaSelect(this, cbxBotella);
    }
    if (Comprobacion.select(cbxConexion)) {
        Comprobacion.alertaSelect(this, cbxConexion);
    } else {
        modelo.setRowCount(0);
        ApiRestRepository apirestrepository = new ApiRestRepository();

        // Registro de la reserva
        int resultado = apirestrepository.registraReserva(idActividad, (int) idCliente, botella);
        modelo2.setRowCount(0);
        apirestrepository.cargarReservas(modelo2, idActividad);

        // Manejo del resultado de la operación
        switch (resultado) {
            case 0:
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error en la inscripción", "Error", JOptionPane.ERROR_MESSAGE);
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "El registro se realizó correctamente", "Registrado", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "El cliente ya se encuentra registrado en la actividad", "Error", JOptionPane.ERROR_MESSAGE);
                break;
        }
        // Fin del ELSE
    
}


        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void busquedaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaClientesMouseClicked
/**
 * Captura la ID del cliente al seleccionarlo en la tabla {@code busquedaClientes} con el ratón.
 * 
 * Este segmento de código determina la fila seleccionada en la tabla usando la posición
 * del ratón y, si la fila es válida (mayor o igual a cero), extrae la ID del cliente
 * de la primera columna de esa fila. A continuación, muestra un cuadro de diálogo con la ID
 * del cliente seleccionado.
 *
 * @param evt el evento de ratón que contiene información sobre la acción de selección.
 */
int fila = busquedaClientes.rowAtPoint(evt.getPoint());
if (fila >= 0) {
    idCliente = busquedaClientes.getValueAt(fila, 0);
    JOptionPane.showMessageDialog(this, idCliente, "hola", JOptionPane.INFORMATION_MESSAGE);
}


        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaClientesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
   

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Reservas dialog = new Reservas(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JTable busquedaClientes;
    private javax.swing.JComboBox<String> cbxBotella;
    private javax.swing.JComboBox<String> cbxConexion;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel foto2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable reservasClientes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
DefaultTableModel modelo;
DefaultTableModel modelo2;
ApiRestRepository apirestrepository = new ApiRestRepository();




    
       
   
}
